import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./style.css"
import Header from "./components/Header";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#CEE1FF] p-10 tracking-[-0.09rem]`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
